
const SUCCESS_CREATION ='Successfully created';
const SUCCESS_UPDATE='Successfully updated';
const SUCCESS_INVITATION_CREATION ='Successfully invited';
const ERROR_INVITATION_CREATION ='Error when inviting people, please make sure they are existing users...';
const ERROR_CREATION ='Error Something went wrong, please retry within few minutes...We currently working on our server';
const ERROR_UPDATE='Error Something went wrong when updating, please retry within few minutes...We currently working on our server.';
const SUCCESS_DELETE ='Successfully deleted';
const ERROR_DELETE ='An error occured when deleting...Please retry within few minutes...We currently working on our server';
const RESPECTING_YOUR_PRIVACY= 'We are committed to protecting and respecting your privacy. This Policy sets out the basis on which any personal data that we collect from you or that you provide to us will be processed on our website. We keep certain basic information when you visit our website and recognize the importance of keeping that information secure and letting you know what we will do with it. You may choose to provide us with information that is considered personal data. The term “personal data” as used in this Policy refers to information such as your name, e-mail address, mailing address, telephone number, or any other data that can be used to identify you. The term “website” or "application" includes this application or website and our associated sites, such as addressmanager.com,api.addressmanager.com';
const COPYRIGHT = '© 2019 Fantech & Life. All rights reserved.This application is published and maintained by Fantech & Life. Unless otherwise indicated, all text and other information on this website are the intellectual property of Fantech & Life.';
const DATA_SECURITY_AND_CONFIDENTIALITY = 'We take the security and confidentiality of your personal data very seriously. We use up-to-date data storage and security techniques to protect your personal information from unauthorized access, improper use or disclosure, unauthorized modification, unlawful destruction, or accidental loss. All processors of personal data and any third parties we engage to process your personal information are obligated to respect the confidentiality of your information. We keep your personal data for only as long as reasonably necessary for the purposes for which it was collected or to comply with any applicable legal reporting or document retention requirements.';
const PRIVACY =  'IMPORTANT: BY USING OUR WEBSITE/APPLICATION AND/OR BY PROVIDING US WITH ANY PERSONAL DATA, YOU GIVE YOUR EXPLICIT CONSENT THAT ALL PERSONAL DATA THAT YOU SUBMIT MAY BE PROCESSED BY US IN THE MANNER AND FOR THE PURPOSES DESCRIBED IN THE FOLLOWING PRIVACY POLICY AND IN COMPLIANCE WITH THE EFFECTIVE LAWS AND REGULATIONS ON PERSONAL DATA';
const TERMS_OF_USE = 'Welcome! This application is provided to manage your personnal activities. We want others to benefit from our application site too, but please do not reproduce its contents on another website or application. You may share what you have learned by directing others to this website or application as outlined in the Terms of Use below.';
const POLICY_UPDATE = 'We are continually improving and adding new functionality and features to this website, and improving and adding to our existing services. Because of these ongoing changes, as well as changes in the law and the nature of technology, our data practices will change from time to time. When it proves necessary to change our Policy, we will post any changes on this page so that you are always aware of what information we collect and how we use it.';